# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: yzcn.github.io
date_format: "ordinal"
title: 黑熊怪
subtitle: ""
description: "yzcn's blog"
keywords: c, cpp, c++, linux
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 黑熊怪
organization: 
organization_url: 
github_username: yzcn
location: Zhengzhou, China
email: txunhuan@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yzcn/yzcn.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yzcn
    repo: yzcn.github.io
    oauth:
        client_id: 896ef08b1fd205e6eb83
        client_secret: 9bd241a2f1e00f47bb687f37ef39debde6ad47f5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yzcn
    repo: yzcn.github.io
    clientID: 896ef08b1fd205e6eb83
    clientSecret: 9bd241a2f1e00f47bb687f37ef39debde6ad47f5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-110226116-1
